from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    args = [
        DeclareLaunchArgument("motor_base_url", default_value="http://127.0.0.1:8000"),
        DeclareLaunchArgument("enable_send", default_value="false"),
        DeclareLaunchArgument("gait_hz", default_value="60.0"),
        DeclareLaunchArgument("step_hz", default_value="0.55"),
        DeclareLaunchArgument("stand_sec", default_value="3.0"),
        DeclareLaunchArgument("warmup_sec", default_value="4.0"),
        DeclareLaunchArgument("stand_kp", default_value="38.0"),
        DeclareLaunchArgument("stand_kd", default_value="4.0"),
        DeclareLaunchArgument("send_kp", default_value="38.0"),
        DeclareLaunchArgument("send_kd", default_value="4.2"),
        DeclareLaunchArgument("send_speed", default_value="0.0"),
        DeclareLaunchArgument("send_torque", default_value="0.0"),
        DeclareLaunchArgument("http_timeout", default_value="0.08"),
        DeclareLaunchArgument("lift_height", default_value="0.026"),
        DeclareLaunchArgument("front_lift_height_gain", default_value="1.18"),
        DeclareLaunchArgument("rear_lift_height_gain", default_value="1.08"),
        DeclareLaunchArgument("front_calf_lift_extra", default_value="0.072"),
        DeclareLaunchArgument("rear_calf_lift_extra", default_value="0.070"),
        DeclareLaunchArgument("rear_thigh_lift_extra", default_value="0.018"),
        DeclareLaunchArgument("front_thigh_lift_scale", default_value="0.42"),
        DeclareLaunchArgument("stomp_touchdown_push_m", default_value="0.004"),
        DeclareLaunchArgument("front_stomp_touchdown_push_m", default_value="0.005"),
        DeclareLaunchArgument("front_companion_press_m", default_value="0.005"),
        DeclareLaunchArgument("front_companion_calf_push", default_value="0.018"),
        DeclareLaunchArgument("support_stand_tall_m", default_value="0.004"),
        DeclareLaunchArgument("diagonal_support_extra_m", default_value="0.004"),
        DeclareLaunchArgument("front_swing_body_x_shift", default_value="-0.018"),
        DeclareLaunchArgument("rear_swing_body_x_shift", default_value="0.040"),
        DeclareLaunchArgument("body_y_shift", default_value="0.026"),
        DeclareLaunchArgument("body_x_foot_scale", default_value="0.12"),
        DeclareLaunchArgument("active_foot_body_x_scale", default_value="0.04"),
        DeclareLaunchArgument("hip_body_y_scale", default_value="0.55"),
        DeclareLaunchArgument("support_hip_inward_amp", default_value="0.014"),
        DeclareLaunchArgument("swing_hip_relief_amp", default_value="0.004"),
        DeclareLaunchArgument("hip_default_scale", default_value="0.38"),
        DeclareLaunchArgument("hip_default_inward_offset", default_value="0.010"),
        DeclareLaunchArgument("rear_hip_default_outward_offset", default_value="0.006"),
        DeclareLaunchArgument("rear_thigh_default_back_offset", default_value="0.035"),
        DeclareLaunchArgument("front_calf_min_rad", default_value="-1.12"),
        DeclareLaunchArgument("max_target_rate_rad_s", default_value="2.4"),
        DeclareLaunchArgument("max_delta", default_value="0.65"),
        DeclareLaunchArgument("torque_warn_nm", default_value="6.0"),
    ]

    node = Node(
        package="mydog_policy",
        executable="fanfan_step_in_place_node",
        name="fanfan_step_in_place_node",
        output="screen",
        parameters=[
            {
                "motor_base_url": LaunchConfiguration("motor_base_url"),
                "enable_send": LaunchConfiguration("enable_send"),
                "gait_hz": LaunchConfiguration("gait_hz"),
                "step_hz": LaunchConfiguration("step_hz"),
                "stand_sec": LaunchConfiguration("stand_sec"),
                "warmup_sec": LaunchConfiguration("warmup_sec"),
                "stand_kp": LaunchConfiguration("stand_kp"),
                "stand_kd": LaunchConfiguration("stand_kd"),
                "send_kp": LaunchConfiguration("send_kp"),
                "send_kd": LaunchConfiguration("send_kd"),
                "send_speed": LaunchConfiguration("send_speed"),
                "send_torque": LaunchConfiguration("send_torque"),
                "http_timeout": LaunchConfiguration("http_timeout"),
                "lift_height": LaunchConfiguration("lift_height"),
                "front_lift_height_gain": LaunchConfiguration("front_lift_height_gain"),
                "rear_lift_height_gain": LaunchConfiguration("rear_lift_height_gain"),
                "front_calf_lift_extra": LaunchConfiguration("front_calf_lift_extra"),
                "rear_calf_lift_extra": LaunchConfiguration("rear_calf_lift_extra"),
                "rear_thigh_lift_extra": LaunchConfiguration("rear_thigh_lift_extra"),
                "front_thigh_lift_scale": LaunchConfiguration("front_thigh_lift_scale"),
                "stomp_touchdown_push_m": LaunchConfiguration("stomp_touchdown_push_m"),
                "front_stomp_touchdown_push_m": LaunchConfiguration("front_stomp_touchdown_push_m"),
                "front_companion_press_m": LaunchConfiguration("front_companion_press_m"),
                "front_companion_calf_push": LaunchConfiguration("front_companion_calf_push"),
                "support_stand_tall_m": LaunchConfiguration("support_stand_tall_m"),
                "diagonal_support_extra_m": LaunchConfiguration("diagonal_support_extra_m"),
                "front_swing_body_x_shift": LaunchConfiguration("front_swing_body_x_shift"),
                "rear_swing_body_x_shift": LaunchConfiguration("rear_swing_body_x_shift"),
                "body_y_shift": LaunchConfiguration("body_y_shift"),
                "body_x_foot_scale": LaunchConfiguration("body_x_foot_scale"),
                "active_foot_body_x_scale": LaunchConfiguration("active_foot_body_x_scale"),
                "hip_body_y_scale": LaunchConfiguration("hip_body_y_scale"),
                "support_hip_inward_amp": LaunchConfiguration("support_hip_inward_amp"),
                "swing_hip_relief_amp": LaunchConfiguration("swing_hip_relief_amp"),
                "hip_default_scale": LaunchConfiguration("hip_default_scale"),
                "hip_default_inward_offset": LaunchConfiguration("hip_default_inward_offset"),
                "rear_hip_default_outward_offset": LaunchConfiguration("rear_hip_default_outward_offset"),
                "rear_thigh_default_back_offset": LaunchConfiguration("rear_thigh_default_back_offset"),
                "front_calf_min_rad": LaunchConfiguration("front_calf_min_rad"),
                "max_target_rate_rad_s": LaunchConfiguration("max_target_rate_rad_s"),
                "max_delta": LaunchConfiguration("max_delta"),
                "torque_warn_nm": LaunchConfiguration("torque_warn_nm"),
            }
        ],
    )

    return LaunchDescription(args + [node])
